### ISSUE TITLE
Constant crashing when trying to C/P builds into tree.

### ISSUE THREAD

**Issue by Morning32** [EmmittJ/PoESkillTree#386]
Latest issue with this that i cannot figure out what is wrong. Ive deleted both folder in documents and %appdata and still everything i C/P the skill tree im trying to use it just crashed. [using the pathfinder tree just straight C/p from here](https://www.pathofexile.com/forum/view-thread/1740806). Did it twice, ill upload the crash reports.

[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/504112/debug.txt)

**Comment by brather1ng** [comment]
It doesn't work with links to fullscreen trees it seems. [This one](https://www.pathofexile.com/passive-skill-tree/AAAABAIDAQG8BbUGIAceDXwN0Q5IDlwRLxFQEZYV1xslG8ggbiLqIvQknST9KPoqCyo4KwosvzB8NAo1uTdMN9Q9X0QNRX5GcUlRSbFLrkyzUDBRR1JTVmNW-lfJWHVd8l9qX7BiWmNDavpsC20ZbWxvnnBScLt0oHcHd9d_K3-Af8aDCYTFhq6HE4nTjAuMNo2Sjb-P-pMnlS6XlZf0mK2bjZu1nKSet6Evpyu0DLVIuXy-isM6x53I8MrTzqjP3dAf0NDTftfP2VvbXuOE51TndOjW6QLquutj7BjssO0_7g7veu-I7-vw1fFt8Yr3Pfk3_xD_3g==) should work.

I'll fix it now.

**Comment by brather1ng** [comment]
Fixed! Thanks for the report.

It would actually crash with any tree url not starting with https://www.pathofexile.com/passive-skill-tree/.

Interesting discovery: The "Load Tree" button doesn't do anything. Just focusing anything outside the url text box will load the tree. I think it should stay there even if it doesn't do anything: it is the most intuitive way to move focus outside of the text box.

**Comment by EmmittJ** [comment]
That seems weird...this was never a problem. I had a fairly nice regex
going that should match a lot of different trees and full screen was
definitely in it.

**Comment by brather1ng** [comment]
Yep, that method simply wasn't called.

**Comment by EmmittJ** [comment]
This is still an issue then. If trees aren't being parses as it says on the tin we have a problem. When did tree loading change?

**Comment by EmmittJ** [comment]
Pretty sure the load build button should be the one doing the actual work. We don't want a build try and load if they start accidentally typing in that field.

**Comment by brather1ng** [comment]
Yeah, happened when I bound the text box directly to the CurrentBuild.TreeUrl property. They should probably be separated again.
